### ISSUE TITLE
Multilingual Support

### ISSUE THREAD

**Issue by firedeepan** [mozilla-services/react-jsonschema-form#773] opened 2017-11-21 13:39 UTC
How to specify localized text for Title and Error messages?

**Comment by iplus26** [comment] 2017-11-26 08:11
Checkout [Custom error messages](https://github.com/mozilla-services/react-jsonschema-form#custom-error-messages) in README.

In my case, I need Chinese messages, so I "translate" the `errors` object.
```typescript
function transformErrors(errors: Array<{ name: string, message: string, schema: any, argument: string }>) {
  return errors.map(error => {
    switch (error.name) {
      case 'minLength':
        error.message = `最小长度为${error.schema.minLength}`
        break;
      case 'required':
        try {
          const { argument } = error
          error.message = `请填写${error.schema.properties[argument].title}`
        } catch (e) {  }
        break;
    }
    return error;
  });
}

export { transformErrors }
```

It does the job but I also expect a more elegant way

**Comment by glasserc** [comment] 2018-01-10 21:00
Duplicate of #739.

**Closed by glasserc** 2018-01-10 21:00 UTC
