### ISSUE TITLE
Form validation errors stay on screen when re-rendering due to changed properties

### ISSUE THREAD

**Issue by sbusch** [mozilla-services/react-jsonschema-form#793] opened 2017-12-15 11:27 UTC
### Prerequisites

- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);

### Description

Form validation errors stay on screen when re-rendering due to changed properties

The component which includes <Form> maintains form data internally and assigns it as formData prop to the <Form> component.

When user submits the form an gets validation errors, the errors stay on screen even after submitting valid data (validation succeeds, onSubmit fires).

I think internal <Form> state gets messed up when re-rendering due to changed properties.

Testing with `_.cloneDeep` (as proposed in #306) didn't help.

Although I think handling `onChange` should be required only for `liveValidate` mode, adding `onChange` with or without `_.cloneDeep` didn't help, either.

Maybe related:
* #306 

### Steps to Reproduce

Here's a fiddle with a mimimal case demonstrating this behavior:

https://jsfiddle.net/h2o/vz4nexpx/
(lodash available in `_` variable)

1. enter invalid data
2. submit form
3. correct data
4. submit form again

#### Expected behavior

Validation errors are hidden when submitting valid data.

#### Actual behavior

Validation errors remain on screen.

### Version

1.0.0

**Comment by edi9999** [comment] 2018-01-13 15:34
Thanks for the issue. Did you find out what is causing this issue ?

**Comment by sbusch** [comment] 2018-01-13 18:17
Unfortunately not, had no time yet to take a deeper look.

And I'm new to React...

**Comment by stepbackj** [comment] 2018-02-20 21:58
@edi9999 I've resolved this issue in my pull request. Can you please take a look when you get a chance?

**Comment by glasserc** [comment] 2018-04-18 17:27
I think this is a dupe of #315.

**Closed** 2018-04-18 18:56 UTC
Labels: bug
