### ISSUE TITLE
Render empty array item fields when minItems is specified

### ISSUE THREAD

**Issue by n1k0** [mozilla-services/react-jsonschema-form#434] opened 2016-12-28 10:20 UTC
When `minItems` is specified for an array field, we should initialize the form with as many empty fields as the number specified.

**Comment by glasserc** [comment] 2017-02-24 01:11
This is closed by #434.

**Closed by glasserc** 2017-02-24 01:11 UTC
Labels: easy-pick, enhancement, help wanted

**Comment by n1k0** [comment] 2017-03-21 09:04
Released in [v0.44.0](https://github.com/mozilla-services/react-jsonschema-form/releases/tag/v0.44.0).

**Comment by dropdevcoding** [comment] 2017-03-27 13:07
I recently upgraded from 0.43.0 to 0.45.0 and it seems that this change causes unexpected behaviour in my application:

I have defined an array with minItems: 1 but this array is NOT marked as required. This will cause validation errors when submitting again without changing anything, since the changed default behaviour produces invalid state.

Could you please add an additional check respecting the required property before applying the newly introduced default behaviour?

**Comment by n1k0** [comment] 2017-03-28 10:25
In my own understanding of the JSON schema spec, `required` and `minItems` are not interdependent. You can have this schema:

```js
{
  type: "object",
  properties: {
    foo: {
      type: "array",
      items: {type: "number"},
      minLength: 1
    }
  }
}
```

And both `{}` and `{foo: [42]}` would be valid payloads against that schema, while `{foo: []}` would not.

**Comment by spacebaboon** [comment] 2017-03-30 15:31
I'm having a problem with this change too. We're using an array with `"ui:widget": "checkboxes"` to render a checkbox group in a form, and `minItems=1` to validate that the user has selected at least one.

It can be seen easily in the playground, under Arrays. Add `"minItems": 1` to the `multipleChoicesList` section, and then delete the entry for `multipleChoicesList` in the formData section. When a form is first rendered, we have no formData, so this is the initial state, not an empty array.

Now click one of the checkboxes in the live demo and see what happens to the formData. A null entry is added after the selected values. Make it `"minItems": 2` and 2 null entries are added.

I thought that I could set a default for the field, by adding `default: []` in the schema, but this changes the nulls to empty arrays. 

It seems like minItems is serving two different purposes here. And perhaps default too. Perhaps `default` inside `items` could define the item default, and `default` outside could be the default for the array itself?

So my only option, unless I'm missing something, is to programmatically initialise the formData to be an empty array where I find an array type in the schema.

**Comment by spacebaboon** [comment] 2017-04-03 15:03
I think I'll post my comment above as a new issue, it looks like a bug to me, and this issue has already been closed.
