### ISSUE TITLE
Force Refresh : can't force a refresh of the form by supplying new formdata 

### ISSUE THREAD

**Issue by vincentsixty** [mozilla-services/react-jsonschema-form#771] opened 2017-11-16 21:06 UTC
//My code reconstructs that "formData" json every time" and the from does not get redrawn, why ?  
` `ret:`
      <Form schema={schema}
            uiSchema={uiSchema}
            formData={formData}
            onSubmit={onSubmit}
            fields={fields}
            ArrayFieldTemplate={ArrayFieldViewer}
            formContext={formcontext}>
        <div></div>
      </Form>
 
`

**Comment by TBearSantaCruz** [comment] 2017-11-17 16:34
Would you be able to try running your code against version 0.43.0?  If your code renders properly, this may be a duplicate of issue [#669](https://github.com/mozilla-services/react-jsonschema-form/issues/669)

**Comment by epicfaace** [comment] 2019-03-16 23:13
Closing this issue due to inactivity. Let me know if you have any more questions @vincentsixty though.

**Closed by epicfaace** 2019-03-16 23:13 UTC
