### ISSUE TITLE
Add sortable feature to ArrayField

### ISSUE THREAD

**Issue by gkourupes** [mozilla-services/react-jsonschema-form#233] opened 2016-06-08 19:54 UTC
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme).

### Description

In my app, we add many items using array field, and then save it.  We can then edit the saved data later.  Often we run into the problem of wanting to rearrange the order of the array items.  This involves a lot of delete and add which is horribly cumbersome!

I'm looking into making a custom UI widget for the array to allow this capability.  I did this before for a file field, and now I see you have added file field to your project.

So, in the interest of preventing duplicate work, would it be possible to add sortable capabilities to the array field ui widget?  Preferably drag and drop, but up/down arrow moving would work.  

### Steps to Reproduce

1. Create an array field
2. Add a bunch of items
3. Rearrange those items

#### Expected behavior

I'd expect the sortable ordering to be represented in a new order in the formData.

#### Actual behavior

You have to delete item(s) from the array, and then add them again in the order you want.

### Version
0.29.1

**Comment by n1k0** [comment] 2016-06-08 20:25
Duplicate of #217.

**Closed by n1k0** 2016-06-08 20:25 UTC
