### ISSUE TITLE
Ability to include React components within the form

### ISSUE THREAD

**Issue by lardissone** [mozilla-services/react-jsonschema-form#810] opened 2018-01-12 15:38 UTC
I would like to be able to include simple components in a form, like titles or descriptions.

Is that possible today?

Example: 
![image](https://user-images.githubusercontent.com/59826/34882460-732c30c8-f795-11e7-9fff-f4d149ab3151.png)

**Comment by lardissone** [comment] 2018-01-12 16:10
I'm currently using custom fields that don't do anything but renders the components.

**Comment by edi9999** [comment] 2018-01-13 15:09
That is possible but only if you change your JSONSchema , you can see a live Example by going to : 

https://mozilla-services.github.io/react-jsonschema-form/ and then on the "property dependencies".

There is a suggestion to make it possible to do this without changing the JSONschema (only with the UISchema) : https://github.com/mozilla-services/react-jsonschema-form/issues/784

I'm closing this as a duplicate of that issue.

**Closed by edi9999** 2018-01-13 15:09 UTC

**Comment by lardissone** [comment] 2018-01-15 14:04
@edi9999 I don't think that solves the problem. It just allows you to add a title and description to a fieldset. In my screenshot looks similar, but I was speaking about any kind of content.

**Comment by edi9999** [comment] 2018-01-15 14:40
> I'm currently using custom fields that don't do anything but renders the components.

Then I think that is the best thing you could be doing.

**Comment by YaoKaiLun** [comment] 2019-01-28 01:35
@edi9999 For beautify the style, i have to change my data structure, it's too awkward :( .

**Comment by glasserc** [comment] 2019-02-04 17:08
I would recommend not using `react-jsonschema-form` if you are trying to implement a specific form. `react-jsonschema-form` is a tool for building forms without any knowledge of the form you are trying to build. It is not meant to replace writing HTML.
