### ISSUE TITLE
Unsupported field schema "anyOf"

### ISSUE THREAD

**Issue by jazzido** [mozilla-services/react-jsonschema-form#648] opened 2017-07-25 21:44 UTC
### Description

I'm trying to build a form from [vega-lite's JSON Schema](https://vega.github.io/schema/vega-lite/v2.0.0.json). 

### Steps to Reproduce

1. Get [vega-lite's JSON Schema](https://vega.github.io/schema/vega-lite/v2.0.0.json)
2. Paste it on the JSONSchema field in the Playground
3. set UISchema and formData to `{}`

#### Actual behavior

![image](https://user-images.githubusercontent.com/27584/28595167-a61ee5c2-7160-11e7-9f8e-bf86a9332341.png)

### Version

Both 0.49.0 and e94cb08c5db88b03c940b44ef65e73704f67bff3 (`master` at the time of submitting this report) fail with the same error message.

Thanks!

**Comment by n1k0** [comment] 2017-07-25 23:07
Duplicate of #52, ongoing implementation is happening in #417.

**Closed by n1k0** 2017-07-25 23:07 UTC

**Comment by jazzido** [comment] 2017-07-25 23:10
thanks @n1k0 

Is #417 still active? Has been quiet for the last couple months…

**Comment by n1k0** [comment] 2017-07-25 23:13
Indeed, though as stated in the comments (afaicr), Mozilla doesn't need this feature so it should be contributed by someone else. Feel free to take over the work and contribute if you're interested in seeing this becoming real :)
