### ISSUE TITLE
label of input field

### ISSUE THREAD

**Issue by ofirsa** [mozilla-services/react-jsonschema-form#290] opened 2016-07-24 08:19 UTC
Hi All,
I have start to use this nice react component, and it is working great.
I would like to know if it is possible the place the label for an input field to the left of the input field and not above the input field (as the default behavior).
it will save a lot of space in the form.
Thanks
Saar Ofir

**Comment by n1k0** [comment] 2016-08-16 11:50
Duplicate of #301, where some comments have been made already.

**Closed by n1k0** 2016-08-16 11:50 UTC

**Comment by mplis-jetsetter** [comment] 2016-08-19 16:22
@ofirsa now that #304 has landed, you can accomplish this by doing something like this:

```js
function CustomFieldTemplate(props) {
  const {id, classNames, label, help, required, description, errors, children} = props;
  return (
    <div className={classNames}>
      <label htmlFor={id} className="col-sm-2 control-label">{label}{required ? "*" : null}</label>
      <div className="col-sm-10">
        {children}
      </div>
      {errors}
    </div>
  );
}
```
