### ISSUE TITLE
Add support for "autocomplete" at the field level

### ISSUE THREAD

**Issue by Eric24** [mozilla-services/react-jsonschema-form#1273] opened 2019-05-03 02:07 UTC
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);

### Description

Add support for `autocomplete` at the field level.

### Steps to Reproduce

1. Something like `"ui:autocomplete": true|false`

#### Expected behavior

Add the `autocomplete` attribute (converting true|false to "on|off") to the `<input>` element. It appears to be a well-supported attribute: https://www.w3schools.com/tags/att_input_autocomplete.asp

#### Actual behavior

Not supported at the field level, only at the form level.

### Version

1.5.0

**Comment by epicfaace** [comment] 2019-05-10 23:51
Thanks for reporting -- this is a duplicate of #906 so let's continue the discussion there.

**Closed by epicfaace** 2019-05-10 23:51 UTC
