### ISSUE TITLE
Custom ui:widget will not alter the formData

### ISSUE THREAD

**Issue by hopewise** [mozilla-services/react-jsonschema-form#1014] opened 2018-08-26 15:31 UTC
### Prerequisites

- [X] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);

### Description

When using `ui:widget` the field will not change the `formData` of the form, unlike when not using `ui:widget` any change in the field will be seen in the `formData` when the form is submitted.

### Suggested solution:

Shall I change the `formData` of the form manually when the field text changes? if so, is there an example to do so?

### Steps to Reproduce

1. Create the class that represent the custom UI, and use the following for render:

```
return (
      <div >
      {this.props.children}   
      </div>
    )
```

2. Add to the `schema.properties` `"City": {type: "string", title:"City"}`
3. Add to the `schema.properties` `"City": { "ui:widget": DefaultInput, classNames: "col-md-4"}`

Where `City` is the name of the custom component.
and `DefaultInput ` is the class that represent the custom ui of field.

#### Expected behavior
To see the value of the custom text field when submit the form:
```
onSubmit = ({formData}) => console.log(formData);
```

#### Actual behavior
What I see is:
```
{City: undefined}
```

### Version
```
1.1.4
```

**Comment by hopewise** [comment] 2018-08-27 08:49
I found that I have to call onChange for props as:

```
onChange={(event) => {        
              props.onChange(event.target.value)      
            }
```

but this will yield into this warning:

> arning: A component is changing an uncontrolled input of type text to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components

**Comment by MatejMazur** [comment] 2018-08-27 12:30
You must keep the same type of value. Because if you firstly render this widget (I suppose that you use `<input>`) without the default value, then actual value will be undefined or null and React doesn't like this.
If you look into the [`BaseInput.js`](https://github.com/mozilla-services/react-jsonschema-form/blob/4a653fc3bf8a4bfa9bab3c33047df1334d63e5cb/src/components/widgets/BaseInput.js#L37) you can see that there is condition which sets the undefined value to the string `""`.

**Comment by epicfaace** [comment] 2019-01-19 04:59
Thanks for the explanation @MatejBransky ! Closing this, but feel free to comment if you have additional questions, @hopewise .

**Closed by epicfaace** 2019-01-19 04:59 UTC

**Comment by AKedar21** [comment] 2019-12-27 07:25
I am using ui:field and created custom component, I am able to set value in the input field but when I click submit it shows like <fieldname> should be string.
@epicfaace Can you please guide in this property should I set the value of the input on props/state so that when I submit the form it will pass to my parent rjsf form.

**Comment by epicfaace** [comment] 2019-12-27 10:00
@akedar21 can you make a new issue with a codepen link so it's easy to reproduce?
