### ISSUE TITLE
Custom component registration value bug

### ISSUE THREAD

**Issue by francisrod01** [mozilla-services/react-jsonschema-form#802] opened 2018-01-08 01:17 UTC
### Description

There are some problems with value from `Custom component registration` in the doc.

* I have a field with `required` prop
* The field lost the focus when I tip the value there.
* When I clean the field, it still continues valid, this is so wrong.

[react-jsonschema-form#custom-component-registration](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#custom-component-registration)

### Steps to Reproduce

1. I start to put the value in the field
2. The field lost the focus
3. I continues to put the value there
4. I click to `submit` button and validate with ok
5. I clean the field and submit the button again
6. The field still continues valid.

```js
generateForm() {
    const widgets = {
        myCustomLocation: (props) => {
            return (
                <input type='text'
                    className='custom'
                    value={props.value}
                    required={props.required}
                    onChange={(event) => props.onChange(event.target.value)} />
            )
        }
    }
```

or the same with a external component:

```js
generateForm() {
  const widgets = {
    myCustomLocation: (props) => {
      return <CustomInput {...props}  />
    }
  }
}
...

import React, { Component } from 'react'

class CustomInput extends Component {
    render() {
        const props = this.props

        return (
            <input type='text'
                className='custom'
                value={props.value}
                required={props.required}
                onChange={(event) => props.onChange(event.target.value)} />
        )
    }
}

export default CustomInput

```

#### Expected behavior

I expect the field works fine.

#### Actual behavior

![image](https://user-images.githubusercontent.com/4691768/34656394-a3f799ce-f400-11e7-958c-45cae500dfa6.png)

### Version

* `react-jsonschema-form`: `1.0.0`
* `react`: `16.2.0`

**Comment by edi9999** [comment] 2018-01-11 09:27
I think this is a duplicate of #788 , do you confirm ?

**Comment by edi9999** [comment] 2018-01-11 10:30
This is also the same as #289

**Comment by francisrod01** [comment] 2018-01-11 16:44
Thank you @edi9999 , what about the focus lost when I put the value in field?

**Comment by edi9999** [comment] 2018-01-13 15:18
Can you send a reproducible example ? Also with your Form, schema/uiSchema

**Comment by francisrod01** [comment] 2018-01-16 11:51
Sure: https://jsfiddle.net/francisrod01/0k53ymw8/8/

In jsfiddle don't have a problem with input validation, so I believe there are a conflict of javascript here.

**Comment by epicfaace** [comment] 2019-03-16 22:58
This issue has been inactive for over a year, so I'm closing this. @francisrod01 please feel free to comment if you're still seeing this issue though.

**Closed by epicfaace** 2019-03-16 22:58 UTC
