### ISSUE TITLE
Custom form element schema data mapping

### ISSUE THREAD

**Issue by zanedev** [mozilla-services/react-jsonschema-form#235] opened 2016-06-13 23:47 UTC
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme).

### Description

Need some assistance here, I cannot figure out how to save custom form element data that does not map directly to the form fields schema.  For example I need to show a single string text field for a google geo suggest autocomplete but I want to save the entire object response from google in formData.  How does one map this to a single schema string field without showing form fields for each object property?  Also should this component be a field or a widget?

**Comment by mplis-jetsetter** [comment] 2016-06-14 14:32
I'd also like some guidance on this as I think I'm having a similar issue.

I'm trying to integrate this library with [react-rte](https://github.com/sstur/react-rte) as a replacement for a textArea widget and I've created a custom field that contains the RichTextEditor component. The problem is that the state of the RTE isn't just represented by the text in the editor (which can be stored in the formData no problem), but as a state object that includes things like the cursor position.

In my application, I'm storing the formData in a Flux store and passing that into the Form whenever there's a change. If I just store the text in the formData, I can create one of these state objects from the text, but I lose the cursor position every time there's a change. It'd be nice if I could just store the RTE state in formData.

**Comment by zanedev** [comment] 2016-06-14 16:08
There must be some way maybe hidden fields on an object field?  Does the form elements always have to map 1 to 1 with the schema?

**Comment by cfitz** [comment] 2016-06-17 21:09
hi,

i'm new to React, here's an example of a service that requests SoundCloud and put it into the FormData: 

https://cfitz.github.io/react-jsonschema-form/
https://github.com/cfitz/react-jsonschema-form/blob/master/playground/app.js

It works, but I would love someone to tell me how I'm doing this wrong.

**Comment by n1k0** [comment] 2016-06-28 14:56
> Need some assistance here, I cannot figure out how to save custom form element data that does not map directly to the form fields schema

This is clearly out of scope with what this lib aims at covering. If you need to attach supplementary data to the formData object, you need to do it outside of the Form component. Alternatively if you need to store custom data retrieved from a google API call, you need to have a matching schema structure to hold them. And if you do this in a custom field, you have total control on its rendering.

**Closed by n1k0** 2016-06-28 14:56 UTC
