### ISSUE TITLE
Getting Uncaught TypeError: a is not a function error on the CDN version of the library.

### ISSUE THREAD

**Issue by rohitbishnoi** [mozilla-services/react-jsonschema-form#994] opened 2018-07-31 12:11 UTC
![screen shot 2018-07-31 at 5 37 23 pm](https://user-images.githubusercontent.com/6151462/43458639-96eb377a-94e8-11e8-8e0d-640110c302d1.png)

Uncaught TypeError: a is not a function
    at Object.<anonymous> (<anonymous>:1:9802)
    at t (<anonymous>:1:385)
    at Object.<anonymous> (<anonymous>:1:9677)
    at t (<anonymous>:1:385)
    at Object.<anonymous> (<anonymous>:1:9626)
    at t (<anonymous>:1:385)
    at Object.<anonymous> (<anonymous>:1:9332)
    at t (<anonymous>:1:385)
    at Object.<anonymous> (<anonymous>:1:9142)
    at t (<anonymous>:1:385)

Note: This used to work 3 days ago, looks like something is broken in the latest version.
 
I am using https://unpkg.com/react-jsonschema-form/dist/react-jsonschema-form.js CDN link.

**Comment by loganvolkers** [comment] 2018-08-28 19:35
Can you confirm that this is still the case? Can you provide a [SSCCE](http://sscce.org/), for example on codesandbox.io?

**Comment by M-Reimer** [comment] 2018-09-06 09:41
I don't know how long this will still be available, but I don't get the errors with:

`    <script scr='https://unpkg.com/react-jsonschema-form@1.0.3/dist/react-jsonschema-form.js'></script>
`

It would be really helpful if Mozilla provided a simple example on how to use the "CDN version" of this library. Just plain HTML with  embedded <script> directly in HTML and *without* JSX.

**Comment by GuyPaddock** [comment] 2018-09-18 04:46
I too am seeing this issue with 1.0.4. It does not happen with 1.0.3.

**Comment by glasserc** [comment] 2018-09-28 16:56
I think this is a duplicate of #991.

**Closed by glasserc** 2018-09-28 16:56 UTC
