### ISSUE TITLE
Reodering within an array

### ISSUE THREAD

**Issue by dapetcu21** [mozilla-services/react-jsonschema-form#243] opened 2016-06-22 09:06 UTC
It would be really useful if you could also reorder elements within an array.

**Comment by n1k0** [comment] 2016-06-22 09:14
Duplicate of #217.

**Closed by n1k0** 2016-06-22 09:14 UTC

**Comment by dapetcu21** [comment] 2016-06-22 09:15
Sorry. I actually searched for a similar issue, but didn't find that one.
