### ISSUE TITLE
Merge the PR #693

### ISSUE THREAD

**Issue by santosguilherme** [mozilla-services/react-jsonschema-form#780] opened 2017-12-04 15:09 UTC
Can anyone merge the PR **[Enhancing Form with grid layout #693](https://github.com/mozilla-services/react-jsonschema-form/pull/693)**?

**Comment by santosguilherme** [comment] 2017-12-11 11:07
Is this project still maintained?

**Comment by glasserc** [comment] 2018-01-10 20:08
Duplicate of #693.

**Closed by glasserc** 2018-01-10 20:08 UTC
