### ISSUE TITLE
Default value does not work within anyOf PG

### ISSUE THREAD

**Issue by goralight** [mozilla-services/react-jsonschema-form#1340] opened 2019-06-29 12:45 UTC
### Prerequisites

- [x] I have read the [documentation](https://react-jsonschema-form.readthedocs.io/);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.
- [x] Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/n1k0/f2y3fq7L/6/) or a [shared playground link](https://mozilla-services.github.io/react-jsonschema-form/) demonstrating the issue.

### Description

When using anyOf, the default value does not get set correctly. This can be seen on the example PG for anyOf 

### Steps to Reproduce

1. Go to [PG link](https://mozilla-services.github.io/react-jsonschema-form/)
2. Select anyOf button
3. Notice how the default value is set for Chuck and Norris. Yet on the form data and on the preview, it has not populated the values

#### Expected behavior

Defaults within anyOf populate the data and preview

#### Actual behavior

Defaults within anyOf do not populate data or preview

### Version

I am using the online PG for now. Example of Json Is below:

```{
  "type": "object",
  "properties": {
    "age": {
      "type": "integer",
      "title": "Age"
    },
    "items": {
      "type": "array",
      "items": {
        "type": "object",
        "anyOf": [
          {
            "properties": {
              "foo": {
                "type": "string"
              }
            }
          },
          {
            "properties": {
              "bar": {
                "type": "string"
              }
            }
          }
        ]
      }
    }
  },
  "anyOf": [
    {
      "title": "First method of identification",
      "properties": {
        "firstName": {
          "type": "string",
          "title": "First name",
          "default": "Chuck"
        },
        "lastName": {
          "type": "string",
          "title": "Last name"
        }
      }
    },
    {
      "title": "Second method of identification",
      "properties": {
        "idCode": {
          "type": "string",
          "title": "ID code"
        }
      }
    }
  ]
}
```

I know this has apparently been done:
https://github.com/mozilla-services/react-jsonschema-form/pull/1304

But within the PG it is still not working correctly.

**Comment by epicfaace** [comment] 2019-06-29 15:44
Duplicate of #1334

**Closed by epicfaace** 2019-06-29 15:44 UTC
