### ISSUE TITLE
Any Of , One OF Array Or Object Does Not Work

### ISSUE THREAD

**Issue by vincentsixty** [mozilla-services/react-jsonschema-form#751] opened 2017-11-01 20:35 UTC
const schema =
       {
            "oneOf": [
                {"$ref": "#/definitions/singleObject"}, // plain object
                {
                    "type": "array", // array of plain objects
                    "items": {"$ref": "#/definitions/singleObject"}
                }
            ],
            "definitions": {
                "singleObject": {
                    "type": 'object',
                    "additionalProperties": false,
                    "properties": {
                        "author": {
                            "type": 'number',
                            "required": true
                        }

                    }
                }
            }
        };

        const formData = [{author: 2}];

**Comment by vincentsixty** [comment] 2017-11-02 20:10
any one ?

**Comment by joshgagnon** [comment] 2017-11-30 00:09
As per the docs, oneOf etc is not supported.  This is deal breaker for me.

**Comment by glasserc** [comment] 2018-01-05 19:07
Duplicate of #52.

**Closed by glasserc** 2018-01-05 19:07 UTC
