### ISSUE TITLE
Can we set error from custom widget??

### ISSUE THREAD

**Issue by jariwalabhavesh** [mozilla-services/react-jsonschema-form#697] opened 2017-09-11 11:10 UTC
### Prerequisites

- [X] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);

### Description

Can we set error from custom widget.???
Basically there is two way to manipulate and handle error:
1. We can transform default error message to our own using `transformErrors`
2. We can validate form data manually for custom validation requirement using `validate`

Example use case:
- I have custom widget which is date-time picker kind.
- I want to validate date from custom widget and need to provide error to form.
I know i can do this using `validate` but i need to write (copy/paste) same validate function for each form. But if it is possible to pass error to form directly from custom widget then we need no to set same validation for multiple form.

I am not getting any kind of `error` property or `setError` function that allow me to set error in form's error object in custom widget.

So is there any way to do it??

Thanks

**Comment by j** [comment] 2017-10-03 18:32
Dang, I just left this same issue.   Oops.

**Comment by glasserc** [comment] 2017-10-06 14:44
Hi, sorry @jariwalabhavesh for taking so long to answer. I thought about it and I guess I would be OK with having additional mechanisms to let developers write validation routines. However, the fact that both you and @j stumbled upon the exact same use case -- validating certain kinds of dates -- I also wonder if it would be simpler to just add better support for validating dates. For example, JSON Schema doesn't support minimum/maximum on dates, but maybe we could add some extensions that provide those fields when operating on date-time fields. Could you elaborate on what kinds of validations you need to perform on dates? I would be happy to review PRs that improve our support in this area.

**Comment by jariwalabhavesh** [comment] 2017-10-31 07:00
Hi @glasserc , 
Very sorry for delay response.
I am having validation like 
- minimum date 
- maximum date,
- date range (i can pass start and end date which will validating selected date to be in this range)

To set error will be helpful to other widget as well when it is come's to custom widget. so user can validate data based on configuration passed to widget.

**Comment by glasserc** [comment] 2018-04-18 18:29
OK, this sounds like a duplicate of #155.

**Closed by glasserc** 2018-04-18 18:29 UTC

**Comment by snirotem** [comment] 2020-12-16 21:42
Hi, i know its an old issue, but after spending couple of days without a hint, maybe here i will finally find an answer.
How can raise an error from within a custom widget ?

i have a form with my custom widgets and also with customer-created widgets.
some of those customer-created widgets may have custom validations, and i need to know how i should instruct them to raise validation errors.

**Comment by M-S-Saurabh** [comment] 2021-07-07 17:15
Hi @snirotem,
Did you figure out a way to raise error from within a custom widget? I am looking for solutions to the same problem.

**Comment by epicfaace** [comment] 2021-07-07 17:35
I don't think it's currently possible. You may have to modify the `validate` function somehow instead.

**Comment by Morriz** [comment] 2022-02-18 12:52
This is a big omission iyam, and should be put on the roadmap. Isn't it essential that a component governing user input can raise errors? And this is _not_ a dupe of #155 as that pertains to jsonschema errors.

This should be re-opened as this is about custom widgets being able to raise errors (not all errors are schema based, i.e. when a widget is allowing schemaless yaml|json|whatever, but validates the input for correctness)

**Comment by Morriz** [comment] 2022-02-18 16:30
Done: #2718
