### ISSUE TITLE
Support bootstrap v4

### ISSUE THREAD

**Issue by vinhlh** [mozilla-services/react-jsonschema-form#299] opened 2016-08-06 08:19 UTC
Should support bootstrap v4 (alpha 3)💃

**Comment by n1k0** [comment] 2016-08-15 09:53
Yeah that'd be great :) Would you like to work on this?

**Comment by zenflow** [comment] 2017-09-30 02:20
In beta now

**Comment by burtonator** [comment] 2018-09-18 14:13
Could we get an updated status of Bootstrap v4 support? 

Are you working on it? When will it be done? etc.  Love this project but the schema form stuff is off in a ghetto right now in my project because our other webapps are using v4

**Comment by glasserc** [comment] 2018-09-26 20:22
This is either a duplicate of a zillion other bugs, or a duplicate of #899.

**Closed by glasserc** 2018-09-26 20:22 UTC
