### ISSUE TITLE
When updating the uiSchema - the form will not re-rendered

### ISSUE THREAD

**Issue by dekelb** [mozilla-services/react-jsonschema-form#517] opened 2017-03-19 23:16 UTC
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

If the uiSchema is updated after the component is mounded - the render function will not be called again.
In the following case:

    <Form 
        schema={this.state.schema}
        uiSchema={this.state.uiSchema}
        liveValidate
    />

When there is a change in `this.state.uiSchema` I would expect the component to re-render, however for some reason it doesn't happen.

### Steps to Reproduce

Here is a working example:
https://jsfiddle.net/bLvk8jgy/

1. Click on the `Change uiSchema` button (nothing happen)
2. Click on the `Change Schema` button (the description field will be removed)

#### Expected behavior

I would expect the `<Form>` to re-render.
The `uiSchema` will not have the `"ui:widget": "textarea"` for the description so I would expect this field to change back to normal string field.

#### Actual behavior

Nothing happen.

### Version
0.43.0

**Comment by n1k0** [comment] 2017-03-20 08:50
It seems to be an issue with mutating the reference to the uiSchema object stored in state; cloning just works https://jsfiddle.net/n1k0/f79q7xkd/1/

I suspect a weird issue with mutability, and it's totally unclear to me why your example works for the schema but not for the uiSchema. I don't know what to do with this issue, I'm tempted to close it but I hate not figuring out everything before doing so.

**Comment by dekelb** [comment] 2017-03-20 09:02
@n1k0 Thanks for your fast reply.
As you already notices - something doesn't really makes sense there and I don't think this should be closed. It a bug (and a really annoying one) and I really think it should be fixed.

I think it is related to the `shouldRender` function the checks the values of the props/state, but I couldn't figure out the cause there.

BTW, if I try to `forceUpdate` the component it still doesn't work :(

**Comment by n1k0** [comment] 2017-03-20 09:04
I wonder if we're not hitting some React bug of some sort, as this doesn't make ANY sense. See my last jsfiddle, how on Earth would deleting an object property right from the state object reference would prevent actually updating state next?

**Comment by dekelb** [comment] 2017-03-20 09:08
Yeah, I checked your jsfiddle, it doesn't make sense.
Can you mark this as a bug? It might get more comments from others.

**Comment by n1k0** [comment] 2017-03-20 09:11
Well it works just fine with plain React, so I think that's a bug with our lib :( https://jsfiddle.net/n1k0/cfcswq0m/1/

**Comment by dekelb** [comment] 2017-03-20 09:15
Well - the problem is that it works with the `schema` and with the `formData` objects but not with the `uiSchema` one, so I guessed it's a bug with this specific lib.
Any idea why the `forceUpdate()` doesn't work? It might help narrow down the cause.

**Comment by n1k0** [comment] 2017-03-20 09:23
Look at this one, how beautiful is this? https://jsfiddle.net/bLvk8jgy/2/

**Comment by n1k0** [comment] 2017-03-20 09:30
We may be hitting a silly JavaScript oddity:

```js
> a = {a: 1}
Object {a: 1}
> a === a
true
> delete a.a
true
> a === a
true
```

**Comment by dekelb** [comment] 2017-03-20 09:40
I guess this should require some workaround (or code change).

**Comment by n1k0** [comment] 2017-03-20 09:40
That actually may be a bug in our `deepEquals` implementation indeed.

**Comment by n1k0** [comment] 2017-03-20 09:45
Not that meanwhile, destructuring a spread rest property object solves your issue:

```js
    changeUiSchema() {
      // popping out the description property
    	let {description, ...uiSchema} = this.state.uiSchema;
      
      this.setState({ uiSchema })
    }
```

Also, the React docs state that directly altering component state properties is [a bad practice](https://facebook.github.io/react/docs/react-component.html#state).

**Comment by dekelb** [comment] 2017-03-20 09:54
This will work only if I remove property from the `uiSchema`, however if I change a nested property in a child of the `uiSchema` it will not work :(

**Comment by n1k0** [comment] 2017-03-20 10:00
You have to ensure the new uiSchema object passed to setState doesn't share the same reference, eg. https://jsfiddle.net/f79q7xkd/4/

**Comment by dekelb** [comment] 2017-03-20 10:05
Well, using the following didn't work as expected:

    const {...uiSchema} = this.state.uiSchema;
    console.log(uiSchema == this.state.uiSchema); // false
    uiSchema.description['classNames'] = 'plop'
    this.setState({ uiSchema })

https://jsfiddle.net/f79q7xkd/5/

**Comment by n1k0** [comment] 2017-03-20 10:08
Sorry if it was unclear, that's what I tried to explain in my previous comment; you need to ensure *nested* object references are different, so the render check returns an accurate result.

**Comment by n1k0** [comment] 2017-03-20 10:11
Note that `const {...uiSchema} = this.state.uiSchema;` will not **deeply** clone an object, just its first-level properties. Yeah, I know, but it's JavaScript.

**Comment by n1k0** [comment] 2017-03-24 09:44
After having given a lot of thought to this, I feel like this is both a JavaScript and React issue, and I couldn't come with a simple and efficient way to circumvent this behavior when manually mutating the state object -- especially when it's clearly documented as a dangerous practice in the React docs.

I'm closing for now, though feel free to reopen if you have a better plan in mind and are willing to work on provide a fix.

**Closed by n1k0** 2017-03-24 09:44 UTC

**Comment by athersharif** [comment] 2017-07-28 22:01
Just came across this. Probably not that helpful but instead of using `delete`, using something like `omit` from `lodash` would solve this.

**Comment by jamesdebolt** [comment] 2018-04-25 14:30
Im not sure if it's considered best practice, but I've been able to force a re-render by saving the state to a new variable, clearing the state via `setState({uiSchema: {}})` and then reassigning via `setState({uiSchema: <placeholder variable>})`

**Comment by bgokden** [comment] 2018-05-08 20:41
I can confirm @jamesdebolt 's solution works for me. And I had this problem with Schema (not uiSchema)

**Comment by ben-rabid** [comment] 2018-05-23 22:43
Thanks very much @jamesdebolt - your workaround is working for me too

**Comment by th3happybit** [comment] 2021-11-02 23:36
i faced this issue, updating the state didn't work and setting it to empty cause an error for not mentioning the fields in `'ui:order'`, so I fixed this issue by cloneDeep the new uiSchema:
```js
<RjsForm schema={_.cloneDeep(schema)} uiSchema={_.cloneDeep(uiSchema)}>
  <></>
</RjsForm>
```
Thank you all!

**Comment by nzcodarnoc** [comment] 2024-10-24 01:38
It's 2024 and cloneDeep just saved my life.

**Comment by ba11en** [comment] 2024-10-24 23:36
spread operator is also your friend
