### ISSUE TITLE
oneOf is not supported

### ISSUE THREAD

**Issue by riazkarim** [mozilla-services/react-jsonschema-form#538] opened 2017-04-05 21:34 UTC
I have a schema that accepts either an array of object or a list from an enum.

I'd like it to render as two radio buttons, "Can Complete" and "Can't Complete". Depending on which is selected, I'd like to hide/show different subforms to allow the user to enter the data. Is this possible ?

My draft4 JSON schema achieves this by using "oneOf", but this isn't supported in this rjsf.

**Comment by n1k0** [comment] 2017-04-05 21:36
Duplicate of #52.

An implementation attempt for oneOf has started in #302 but progress hasn't been made since a long time unfortunately. You may want to take over this effort.

**Closed by n1k0** 2017-04-05 21:36 UTC
