### ISSUE TITLE
Multiple types does not work

### ISSUE THREAD

**Issue by henit** [mozilla-services/react-jsonschema-form#700] opened 2017-09-18 07:50 UTC
### Description

Array in types does not work

*From doc:* The value of this keyword MUST be either a string or an array. If it is an array, elements of the array MUST be strings and MUST be unique.

### Steps to Reproduce

Schema:

    example: {
        type: ['string', 'number']
    },

#### Actual behavior

    Unsupported field schema for field root_externalId: Unknown field type string,number.
    {
        "type": [
            "string",
            "number"
        ]
    }

### Version

react-jsonschema-form 0.50.1

**Comment by browne0** [comment] 2017-09-20 16:08
I think you're looking for oneOf instead of type. it would look like

```json
{
  "oneOf": [
    {
       "type": "string"
    },
    {
       "type": "number"
    },
  ]
}
```

**Comment by henit** [comment] 2017-09-21 05:09
Isn't oneOf, allOf and anyOf still unsupported in react-jsonschema-form? In any case, the Json Schema specifications says type can be an array of strings and not just one type. I was just wondering if the error message I experienced was a bug or if the type array feature is not supported yet.

**Comment by glasserc** [comment] 2017-09-22 21:43
That's correct, neither `oneOf`, `anyOf`, or multiple types are supported yet, for largely the same reason. The documentation you quoted is from the JSON Schema spec, not the react-jsonschema-form documentation. Duplicate of #282.

**Closed by glasserc** 2017-09-22 21:43 UTC
