### ISSUE TITLE
Passing errors to custom ui widget

### ISSUE THREAD

**Issue by nouman91** [mozilla-services/react-jsonschema-form#577] opened 2017-05-11 09:29 UTC
### Prerequisites

- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [x] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

I am using react json schema form for multi step form wizard. Kind of like new sign-in form of gmail. I am using custom ui widgets for every fields. So far everything worked out great, except only one hard problem. I am trying to pass errors to custom ui widgets through custom field template. But it is not working for me. Here is how I am rendering children in custom ui field template. 

```jsx
{React.cloneElement(this.props.children, { validationError:"Some Error occurred" })}
```

But `ValidationError` prop is being strippred out of children props. Please help me out in fixing this problem.

**Comment by glasserc** [comment] 2018-04-18 18:39
I think this is a duplicate of #155. Please reopen if not.

**Closed by glasserc** 2018-04-18 18:39 UTC
