### ISSUE TITLE
When a text input is empty with a custom widget, the field in form data is set to empty string

### ISSUE THREAD

**Issue by martinkelly23** [mozilla-services/react-jsonschema-form#974] opened 2018-07-11 19:48 UTC
### Prerequisites

- [ ] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme);
- [ ] In the case of a bug report, I understand that providing a [SSCCE](http://sscce.org/) example is tremendously useful to the maintainers.

### Description

When using a custom widget on a text input and is empty, the field in form data is set to empty string.

### Steps to Reproduce

I follow the custom widget example of the documentation.

Ideally, I'm providing a [sample JSFiddle](https://jsfiddle.net/bw0ffnz4/310/)

#### Expected behavior

When a text input is empty, the field in form data is set to undefined

#### Actual behavior

When a text input is empty, the field in form data is set to empty string.

### Version

1.0.3

**Comment by diversos** [comment] 2018-08-29 14:05
I'm actually having the same problem. I'd expect that, if a field is empty, the json formData wouldn't bring the key at all, but it's giving an empty string, which after brings conflict on the server side, since it's an optional field, but doesn't allow empty strings.
I find myself obliged to iterate over every formData object to remove key value pairs when value is empty.
Can't this be changed?

**Comment by ritchieanesco** [comment] 2018-10-18 00:40
Yep. same here. Is there a workaround for this?

**Comment by glasserc** [comment] 2018-10-19 20:53
Closing as a duplicate of #1052.

**Closed by glasserc** 2018-10-19 20:53 UTC
