### ISSUE TITLE
The form is not updating when the formData prop is changed for an object in an array.

### ISSUE THREAD

**Issue by Chun-Yang** [mozilla-services/react-jsonschema-form#306] opened 2016-08-19 16:48 UTC
### Prerequisites
- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme).
### Description

The form is not updating when the formData prop is changed for an object in an array.
### Steps to Reproduce
1. use the following snippet:

```jsx
  class FormComponent extends React.Component {
    constructor(props) {
      super(props);
      this.state = {
        formData: {
          languages: [
            { code: 'eng', name: 'english' }
          ]
        }
      };
    }

    handleOnChange({ formData }) {
      formData.languages[0].code = 'chn';
      this.setState({ formData });
    }

    render() {
      const jsonSchema = {
        "title": "personData",
        "type": "object",
        "properties": {
          "languages": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "code": {
                  "type": "string"
                },
                "name": {
                  "type": "string"
                }
              }
            }
          }
        }
      };

      return <Form
        liveValidate
        schema={jsonSchema}
        formData={this.state.formData}
        onChange={ args => this.handleOnChange(args) }
        onSubmit={() => {}}
        onError={() => {}} />;
    }
  }

```
1. change the name field.
2. NOTE: if you use lodash.deepClone for the form data like this, the form will be updated correctly:

```jsx
    handleOnChange({ formData }) {
      const newFormData = _.cloneDeep(formData);
      newFormData.languages[0].code = 'chn';
      this.setState({ formData: newFormData });
    }

```
#### Expected behavior

The code should change
#### Actual behavior

The code does not change
### Version

0.39.0

**Comment by n1k0** [comment] 2016-08-19 16:51
> if you use lodash.deepClone for the form data like this, the form will be updated correctly

Well, that's because it's the right way to do it, and you found it :)

What would you suggest the lib to do here? Serialization/deep cloning is very costly operation, I'd rather leave it to  developers ;)

**Comment by Chun-Yang** [comment] 2016-08-19 16:57
I see. The thing is the form works for nested object `{a: {b: 1}}` when I set the value, but it does not work for the specific case above. It seems inconsistent.

I think the problem might come from the custom `deepEquals` function in your utils.js Maybe changing the function or just use a third party library like 'lodash' or 'underscore' may solve the problem?

**Comment by peterholdsworth** [comment] 2016-08-29 08:25
May I point out that the problem is described in detail in the last 4 paragraphs of `shouldComponentUpdate in action` section here https://facebook.github.io/react/docs/advanced-performance.html and that a potentially more performant solution is described in the following section `Immutable-js to the rescue`

**Comment by crumblix** [comment] 2016-12-13 03:12
Came across this problem and Peter's suggestion of using update worked a treat ... thank you Peter!
Wish I'd thought of it myself :)

**Comment by LucianBuzzo** [comment] 2019-02-25 17:31
I'm closing this as I was unable to reproduce this issue using the latest version, see https://codesandbox.io/s/7k9v6v1qyj

**Closed by LucianBuzzo** 2019-02-25 17:31 UTC

**Comment by arindamsaha76** [comment] 2022-08-13 05:30
Hi,

I am new to this. I just tried the example given in the codesandbox. I made small change in the handlechange function.

handleOnChange({ formData }) {
    console.log ("Before", formData.languages[0]);
    if (formData.languages[0].name === "a")
      formData.languages[0].code = "chn";
    console.log ("After", formData.languages[0]);
    this.setState({ formData });
  }

When I type "a" in the name, nothing happen. The moment I add another character in name, value gets updated. Could you please let me know, what I am missing here

Thanks,
Monalisa
