### ISSUE TITLE
Boolean Fields Not Rendering Value Properly

### ISSUE THREAD

**Issue by ClockerZadq** [mozilla-services/react-jsonschema-form#349] opened 2016-10-18 17:39 UTC
### Prerequisites
- [x] I have read the [documentation](https://github.com/mozilla-services/react-jsonschema-form/blob/master/README.md#readme).
### Description

I'll do my best to describe this, hopefully the screenshots paint the picture. I can post some of the code in order to help reproduction, if requested.

The initial state is depicted by the first two images. The setup here is using [Bootstrap stacked tabs](https://react-bootstrap.github.io/components.html#tabs-custom-layout), with each tab rendering a form. The form is stateful, maintaining the formData object for each of state (the parent holds the data as well). Regardless, when switching between these tabs nothing out of the ordinary happens.
![usb_state](https://cloud.githubusercontent.com/assets/3731061/19488825/a4fddda8-9536-11e6-9976-7d58ef1662da.PNG)
![networking_state](https://cloud.githubusercontent.com/assets/3731061/19488826/a52843c2-9536-11e6-9717-03ce357020ea.PNG)

If you notice, the forms are nearly identical. All radio buttons have a value of true. The issue presents itself when a value is switched from either of the tabs as shown below
![usb_state2](https://cloud.githubusercontent.com/assets/3731061/19488938/1979c9a8-9537-11e6-88c2-31649401e7fc.PNG)
![networking_state2](https://cloud.githubusercontent.com/assets/3731061/19488941/1bc44152-9537-11e6-8cd3-74e9f668311d.PNG)

In the pictures, the value of the first field in the first tab switched from true -> false. Now, if I switch to the second tab, the first field doesn't display a value. However, inspecting the formData shows that the value is still true.
{
    "Wifi": true,
    "Bluetooth": true,
    "WiredInternet": true
}

The field returns to display its value if the form is re-rendered. I know this is somewhat specific to my src because of the Layout and such, but I'm not entirely sure what is happening here. I can only attribute this to the rendering itself. 
#### Expected behavior

I expected the fields to display the data that is in the formData object for that form.
#### Actual behavior

The field will render the value in the formData, rather than displaying nothing.
### Version

0.40.0

**Comment by n1k0** [comment] 2016-10-18 17:49
Could you please try to create a minimal reproducible test case? Eg. one without your implementation of tabs, which may get in the way (and if so, I don't think it has anything to do with this lib).

Thanks for your understanding!

**Comment by ClockerZadq** [comment] 2016-10-18 18:06
Agreed about the tabs thing - I'm not sure how else to this other than giving you the data for the forms that I am using. I generate all the forms on the fly based on an user input file. I think that the multiple tabs thing is part of the issue - If you combine the two forms there will be no issue if displayed at once. They must be displayed separately.

**First Picture** 
_**Schema :**_ `{"type":"object","title":"USBDevices","required":["EnableUSBDevices","Devices","CAM","USBPorts"],"properties":{"EnableUSBDevices":{"title":"Enable USB","id":"EnableUSBDevices","type":"boolean"},"Devices":{"title":"Devices","id":"Devices","type":"array","uniqueItems":true,"items":{"type":"string","enum":["Device1","Device2","Device3","Device4","Device5"],"enumNames":["","","","",""]}},"CAM":{"title":"Enable CAM","id":"CAM","type":"boolean"},"USBPorts":{"title":"Enable USB Ports","id":"USBPorts","type":"boolean"}}}`

**_UI :_** `{"EnableUSBDevices":{"ui:widget":"radio","ui:help":""},"Devices":{"ui:widget":"checkboxes","ui:help":""},"CAM":{"ui:widget":"radio","ui:help":""},"USBPorts":{"ui:widget":"radio","ui:help":""}}`

_**formData :**_  `{"EnableUSBDevices":true,"Devices":["Device1"],"CAM":true,"USBPorts":true}`

**Second Picture**
_**Schema:**_ `{"type":"object","title":"Networking","required":["Wifi","Bluetooth","WiredInternet"],"properties":{"Wifi":{"title":"Wifi","id":"Wifi","type":"boolean"},"Bluetooth":{"title":"Bluetooth","id":"Bluetooth","type":"boolean"},"WiredInternet":{"title":"Wired Internet","id":"WiredInternet","type":"boolean"}}}`

**_ui :_** `{"Wifi":{"ui:widget":"radio","ui:help":""},"Bluetooth":{"ui:widget":"radio","ui:help":""},"WiredInternet":{"ui:widget":"radio","ui:help":""}}`

**_formData:_**  `{"Wifi":true,"Bluetooth":true,"WiredInternet":true}`

Does this help?

**Comment by leplatrem** [comment] 2016-10-18 20:48
Can you try to dump the current `formData` in your UI (using `<pre>{JSON.stringify(formData, null, 2)}</pre>` for example) and make sure that it's not a problem of your state?

The easiest way for us to help you would be that set up a jsbin or jsfiddle with a demo of the problem. Look at this one if you need a starting point: https://jsfiddle.net/514r2f18/4/

Thanks for reporting!

**Comment by ClockerZadq** [comment] 2016-10-19 16:47
hey @leplatrem I have been fiddling a snippet of the relevant code along with the actual layout. I'm not by any means a JS guru but here is the [link](https://jsfiddle.net/514r2f18/8/) - The code is written using Babel and transpiled using Browserify, so the source you see is the result of the build command. I can paste the pre-compiled code if thats preferred.

Now the behavior that you see in this link is not exactly the same, but there's still some weirdness going on that I'm guessing is relevant to the behavior I am seeing. I noticed that upon initial rendering I get a lot of warnings about unknown props from the react library, that's newish for me. To reproduce the weird behavior, change the values from one of the tabs and go to another tab, switch values and then go back to the first tab. Hopefully this helps!

**Comment by leplatrem** [comment] 2016-10-26 11:25
Yes, I can see that switching back to the first tab removes the checked values. 

However, there is no way we can debug that code.

Please try to reproduce in a minimalist example, otherwise there isn't much we can do about it. Maybe it's related to #359

**Comment by ClockerZadq** [comment] 2016-10-28 19:31
Yeah what a bummer... Thanks @leplatrem it'll just stay that way I suppose.

**Comment by ClockerZadq** [comment] 2016-11-03 19:25
@leplatrem this issue is really bugging me - I've only noticed this with Radio widgets, Select works as expected. The field is aware of the value is just not displaying it, could this be a bug?

**Comment by leplatrem** [comment] 2016-11-03 20:36
Strange that the problems only occurs with radio widgets :( and in your case with true/false. Have you tried to render the form with checkboxes instead?

See the radio widget is pretty straightforward, we iterate on the enum and set as checked if equals the current value:
https://github.com/mozilla-services/react-jsonschema-form/blob/v0.40.0/src/components/widgets/RadioWidget.js#L17-L18

You'll probably have to dig into the code yourself, I'm sorry :(

**Comment by ClockerZadq** [comment] 2016-11-08 14:51
Yea I'm wondering if the checked var is being determined correctly. That seems like the only thing that would cause this behavior. Is there a guide as to how to build this project? I ran the dist script and looks like everything build yet I have no output.

**Comment by glasserc** [comment] 2016-11-08 18:36
The output should be two files in `dist` -- a minified output and a source map.

**Comment by maartenth** [comment] 2016-11-25 12:02
I am experiencing the same problem with the radio widgets with my form. With a select widget, everything is OK. I am investigating the issue now.

**Comment by maartenth** [comment] 2016-11-25 12:28
https://github.com/facebook/react/issues/7630

**Comment by maartenth** [comment] 2016-11-25 12:35
So this is a known bug in React, explained in detail [in this comment](https://github.com/facebook/react/issues/7630#issuecomment-244101305). It only happens when a new field with the same index (so the same DOM element, since react-jsonschema-form uses the index as `key` in `map()`) switches to a radio button that occurs _earlier_ in the DOM. So in the example above, only the switch from `false` to `true` unchecks both boxes.

**Comment by maartenth** [comment] 2016-11-25 12:54
Do we want to fix this here by moving `checked={checked}` above `name={name}`?

**Comment by n1k0** [comment] 2016-11-25 13:01
That's a temporary situation waiting for a proper fix upstream anyway. If that solves the issue in our lib, that's fine by me :) (just ensure adding a comment so we don't forget about it)

**Comment by maartenth** [comment] 2016-11-25 13:35
In my complex form, this PR fixes the issue.

**Comment by n1k0** [comment] 2016-11-25 13:40
Fixed by #423

**Closed by n1k0** 2016-11-25 13:40 UTC
Labels: bug, question

**Comment by n1k0** [comment] 2016-11-25 13:44
Released along [v0.41.2](https://github.com/mozilla-services/react-jsonschema-form/releases/tag/v0.41.2).

**Comment by maartenth** [comment] 2016-11-25 13:54
Thank you for releasing this so quickly!

**Comment by ClockerZadq** [comment] 2016-12-17 19:52
Thank you guys! Cheers!
